services:
  ollama:
    image: ollama/ollama:rocm
    container_name: ollama
    environment:
      OLLAMA_MODELS: /root/.ollama/models
      # Set for RX 6700s (gfx1032), adjust for your GPU.
      HSA_OVERRIDE_GFX_VERSION: "10.3.0"
      # Makes use of dGPU which goes as "0" on my laptop, YMMV.
      # Change to other indices to switch it to another GPU (e.g. "1" for iGPU).
      HIP_VISIBLE_DEVICES: "0"
    devices:
      - "/dev/kfd"
      - "/dev/dri"
    group_add:
      - video
    volumes:
      - $HOME/.ollama:/root/.ollama:Z
    ports:
      - "11434:11434"
    networks:
      backend:
        ipv4_address: 10.1.0.2

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    environment:
      # Change to `true` if you need auth (login, user registration, etc).
      WEBUI_AUTH: false
      # You might want to enable this on the first start so that OpenWebUI
      # can setup the inital state.
      OFFLINE_MODE: true
      OLLAMA_BASE_URL: http://10.1.0.2:11434
    volumes:
      - $HOME/.open-webui:/app/backend/data:Z
    ports:
      - "3000:8080"
    networks:
      backend:
        ipv4_address: 10.1.0.3

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/16
          gateway: 10.1.0.1
